name: Regression Tests

on: [push, pull_request]

jobs:
  build_iverilog:
    uses: daxzio/setup-eda/.github/workflows/setup_iverilog.yml@main

  build:
    name: Python ${{matrix.python-version}}
    runs-on: ubuntu-latest
    needs: [build_iverilog]
        
    strategy:
      fail-fast: false # So that one fail doesn't stop remaining tests
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Icarus
      uses: actions/cache@v3
      with:
        path: ${{ needs.build_iverilog.outputs.cache_dir }}
        key: ${{ needs.build_iverilog.outputs.cache_key }}
    - name: Add to PATH
      run: |
        echo "${{ needs.build_iverilog.outputs.cache_dir }}/bin" >> $GITHUB_PATH

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Report Icarus Verilog
      run: |
        iverilog -v

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox

    - name: Upload coverage to codecov
      run: |
        pip install codecov
        codecov
